xbtit:
  build: .
  ports:
    - "880:80/tcp"
    - "8443:443/tcp"
  volumes:
    - ./html:/var/www/html
    - ./confphp:/usr/local/etc/php/conf.d
  environment:
    XDEBUG_CONFIG: remote_host=172.17.0.1